name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install-depend
      run: sudo apt-get install -y libx11-dev libxft-dev libxinerama-dev
    - name: make
      run: make -C src/
      
